In [1]:
import asyncio
import nest_asyncio
from playwright.async_api import async_playwright
import pandas as pd
from tqdm.notebook import tqdm

In [2]:
# Full scraper with disabled-next-page check
nest_asyncio.apply()

async def full_scraper_checked(total_pages=1000, csv_filename="employee_reimbursements.csv"):
    async with async_playwright() as p:
        browser = await p.firefox.launch(headless=True)
        page = await browser.new_page()
        url = ("https://data.cityofchicago.org/Administration-Finance/Employee-Reimbursements/g5h3-jkgt/explore/querySELECT%0A%20%20%60voucher_number%60%2C%0A%20%20%60amount%60%2C%0A%20%20%60payment_date%60%2C%0A%20%20%60vendor_name%60%2C%0A%20%20%60description%60%2C%0A%20%20%60department%60%0AORDER%20BY%20%60payment_date%60%20DESC%20NULL%20FIRST/page/filter")
        await page.goto(url)
        
        data = []
        for page_number in tqdm(range(total_pages), desc="Scraping pages"):
            try:
                await page.wait_for_selector("td > div", timeout=15000)
            except:
                print(f"Timeout waiting for page {page_number+1}. Skipping.")
                continue
            
            rows = await page.query_selector_all("tr")
            for row in rows:
                cells = await row.query_selector_all("td")
                if len(cells) >= 6:
                    row_data = {
                        "voucher_number": (await cells[0].inner_text()).strip(),
                        "amount": (await cells[1].inner_text()).strip(),
                        "payment_date": (await cells[2].inner_text()).strip(),
                        "vendor_name": (await cells[3].inner_text()).strip(),
                        "description": (await cells[4].inner_text()).strip(),
                        "department": (await cells[5].inner_text()).strip(),
                    }
                    data.append(row_data)
            
            # Check if next button is disabled
            next_btn = await page.query_selector("forge-icon-button[aria-label='Next page']")
            if next_btn:
                is_disabled = await next_btn.get_attribute("aria-disabled")
                if is_disabled == "true":
                    print("Next button disabled — reached last page.")
                    break
                else:
                    await next_btn.click()
                    await page.wait_for_timeout(3000)
                    await page.wait_for_load_state("networkidle")
            else:
                print("No next button found — stopping.")
                break
        
        await browser.close()
        df = pd.DataFrame(data)
        return df

# Run the scraper
df_new = asyncio.get_event_loop().run_until_complete(full_scraper_checked())

Scraping pages:   0%|          | 0/1000 [00:00<?, ?it/s]

Next button disabled — reached last page.

In [3]:
## Remove $ and , from amount figures to ensure they're read as numbers by Datawrapper and to make the drop duplicates work when I merge new data w old data
df_new['amount'] = df_new['amount'].str.replace('$','')
df_new['amount'] = df_new['amount'].str.replace(',','')
df_new['amount'] = df_new['amount'].astype('float')

### Join new data with existing data (preserving original if duplicates exist)

In [4]:
# This is the existing stuff
df_orig = pd.read_csv("employee_reimbursements.csv")

## make sure the original data amounts are also floats
if df_orig['amount'].dtype == 'str':
    df_orig['amount'] = df_orig['amount'].str.replace('$','')
    df_orig['amount'] = df_orig['amount'].str.replace(',','')
    df_orig['amount'] = df_orig['amount'].astype('float')

## Merge existing with new stuff
df_safe = pd.concat([df_orig, df_new], ignore_index=True)

## Allowing for the potential of mixed date types
df_safe['payment_date'] = pd.to_datetime(df_safe['payment_date'], format='mixed')

df_safe.head()

,voucher_number,amount,payment_date,vendor_name,description,department
0,PV01100100520,34.96,2011-01-07,PATRICK L CAREY,Reimbursement for Phone usage,OFFICE OF THE MAYOR
1,PV01100100523,173.20,2011-01-07,TAMARA MAYBERRY,Travel Reimbursement,OFFICE OF THE MAYOR
2,PV01100100524,133.00,2011-01-07,GERALD ALDER,Travel Reimbursement,OFFICE OF THE MAYOR
3,PV01100100529,422.13,2011-01-18,A JOSEPH DEAL,Travel Reimbursement,OFFICE OF THE MAYOR
4,PV01100100534,85.18,2011-01-24,PATRICK L CAREY,Reimbursement for Phone Usage,OFFICE OF THE MAYOR

In [5]:
df_safe.dtypes

voucher_number            object
amount                   float64
payment_date      datetime64[ns]
vendor_name               object
description               object
department                object
dtype: object

In [6]:
## Now that I can be pretty sure the columns are all the same data types, I'm dropping the duplicates
df_safe = df_safe.drop_duplicates(subset=['voucher_number', 'amount', 'payment_date', 'description'], keep='first')

In [7]:
df_safe = df_safe.sort_values(['payment_date'], ascending=False)
df_safe.head()

,voucher_number,amount,payment_date,vendor_name,description,department
66281,PV57255700781,3670.43,2026-04-28,THOMSON WEST,Online Software Subscription Charge - Aug 2025,CHICAGO POLICE DEPARTMENT
66289,PV57265700279,477.40,2026-04-27,"ZAHRAN, MOHAMMAD H",P320 REPLACEMENT REIMBURSEMENT,CHICAGO POLICE DEPARTMENT
66288,PV57265700282,700.00,2026-04-27,"RYVA, CHRISTOPHER J",P320 REPLACEMENT REIMBURSEMENT,CHICAGO POLICE DEPARTMENT
66287,PV57265700283,624.95,2026-04-27,"SANCHEZ, LIZETTE",P320 REPLACEMENT REIMBURSEMENT,CHICAGO POLICE DEPARTMENT
66286,PV57265700303,70.00,2026-04-27,"KAZIMIERSKI, RICHARD",Reimbursement - National Association of Fire I...,CHICAGO POLICE DEPARTMENT

In [8]:
df_safe.to_csv("employee_reimbursements.csv", index=False)

In [9]:
## Renaming column names for stylistic reasons
df = df_safe.rename(columns={'voucher_number':'VOUCHER NUMBER',
                             'amount':'AMOUNT',
                             'payment_date':'PAYMENT DATE',
                             'vendor_name':'VENDOR NAME',
                             'description':'DESCRIPTION',
                             'department':'DEPARTMENT'})

In [10]:
df.head()

,VOUCHER NUMBER,AMOUNT,PAYMENT DATE,VENDOR NAME,DESCRIPTION,DEPARTMENT
66281,PV57255700781,3670.43,2026-04-28,THOMSON WEST,Online Software Subscription Charge - Aug 2025,CHICAGO POLICE DEPARTMENT
66289,PV57265700279,477.40,2026-04-27,"ZAHRAN, MOHAMMAD H",P320 REPLACEMENT REIMBURSEMENT,CHICAGO POLICE DEPARTMENT
66288,PV57265700282,700.00,2026-04-27,"RYVA, CHRISTOPHER J",P320 REPLACEMENT REIMBURSEMENT,CHICAGO POLICE DEPARTMENT
66287,PV57265700283,624.95,2026-04-27,"SANCHEZ, LIZETTE",P320 REPLACEMENT REIMBURSEMENT,CHICAGO POLICE DEPARTMENT
66286,PV57265700303,70.00,2026-04-27,"KAZIMIERSKI, RICHARD",Reimbursement - National Association of Fire I...,CHICAGO POLICE DEPARTMENT

In [11]:
df.shape

(66290, 6)

### Save csvs for reimbursements by department

In [12]:
groups = df.groupby(by="DEPARTMENT")

keys = groups.groups.keys()

for i in keys:
    dept = groups.get_group(i)
    name = i.lower()
    name = name.replace(" ", "-")
    name = name.replace("'","")
    dept.to_csv(f"docs/dept-csvs/{name}.csv", index=False)

### Making summary df/csv by org

In [13]:
## Make the 'AMOUNT' column a float
if df['AMOUNT'].dtype != float:
    df['AMOUNT'] = df['AMOUNT'].str.replace('$','')
    df['AMOUNT'] = df['AMOUNT'].str.replace(',','')
    df['AMOUNT']= df['AMOUNT'].astype(float)

## Do my grouping and make sure the 'index' (department names) saves as an actual column
## df_dept_sum == df_by_department_summary
df_dept_sum = df.groupby(by='DEPARTMENT').agg(
    TOTAL=('AMOUNT', 'sum'),
    COUNT=('VOUCHER NUMBER', 'size'),
    AVERAGE=('AMOUNT', 'median'))
df_dept_sum = df_dept_sum.reset_index()

df_dept_sum = df_dept_sum.rename(columns={'TOTAL':'TOTAL',
                             'COUNT':'# OF PAYMENTS',
                             'AVERAGE':'AVERAGE AMOUNT'})

## Add formatting so each link in the summary dataset points to its subpage
def make_link(dep):
    folder = (
        dep.lower()
        .replace(" ", "-")
        .replace("'", "")
    )
    return f'<a href="https://hgorledeenn.github.io/Chicago-Reimbursements-site/{folder}/index.html">{dep}</a>'

df_dept_sum['DEPARTMENT'] = df_dept_sum['DEPARTMENT'].apply(make_link)

## Write summary csv
df_dept_sum.to_csv("docs/by_department_summary.csv", index=False)